2021-06-07 01:12:54,321 - INFO - BEGIN (implicit)
2021-06-07 01:12:54,322 - INFO - SELECT "web-management"."user".id AS "web-management_user_id", "web-management"."user".user_name AS "web-management_user_user_name", "web-management"."user".first_nane AS "web-management_user_first_nane", "web-management"."user".last_name AS "web-management_user_last_name", "web-management"."user".full_nane AS "web-management_user_full_nane", "web-management"."user".email AS "web-management_user_email", "web-management"."user".phone AS "web-management_user_phone", "web-management"."user".password AS "web-management_user_password", "web-management"."user".role_id AS "web-management_user_role_id", "web-management"."user".create_date AS "web-management_user_create_date", "web-management"."user".update_date AS "web-management_user_update_date", role_1.id AS role_1_id, role_1.code AS role_1_code, role_1.name AS role_1_name, role_1.create_date AS role_1_create_date, role_1.update_date AS role_1_update_date 
FROM "web-management"."user" LEFT OUTER JOIN "web-management".role AS role_1 ON role_1.id = "web-management"."user".role_id 
WHERE "web-management"."user".email = %(email_1)s AND "web-management"."user".password = %(password_1)s 
 LIMIT %(param_1)s
2021-06-07 01:12:54,322 - INFO - [cached since 5860s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'password_1': '1q2w3e4r', 'param_1': 1}
2021-06-07 01:12:54,396 - INFO - ROLLBACK
2021-06-07 01:29:10,906 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 81, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/pot/project/web-management/backend/app/main.py", line 53, in db_session_middleware
    response = await call_next(request)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pot/project/web-management/backend/app/api/resources/v1/account.py", line 25, in login
    user_db = user_logic.get_user_by_email_and_password_join_role(db_session, form_data.username, form_data.password)
  File "/home/pot/project/web-management/backend/app/databases/logic/user.py", line 20, in get_user_by_email_and_password_join_role
    return db_session.query(User) \
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2750, in first
    return self.limit(1)._iter().first()
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2834, in _iter
    result = self.session.execute(
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1676, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1526, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3215, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2068, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 794, in _checkout
    result = pool._dialect.do_ping(fairy.connection)
  File "/home/pot/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 684, in do_ping
    cursor.execute(self._dialect_specific_select_one)
sqlalchemy.exc.DatabaseError: (psycopg2.DatabaseError) SSL SYSCALL error: Connection timed out

(Background on this error at: http://sqlalche.me/e/14/4xp6)
2021-06-07 10:44:16,936 - INFO - Shutting down
2021-06-07 10:44:17,037 - INFO - Waiting for application shutdown.
2021-06-07 10:44:17,037 - INFO - Application shutdown complete.
2021-06-07 10:44:17,037 - INFO - Finished server process [1698]
2021-06-07 10:44:28,115 - INFO - Started server process [4127]
2021-06-07 10:44:28,115 - INFO - Waiting for application startup.
2021-06-07 10:44:28,116 - INFO - Application startup complete.
2021-06-07 10:44:28,116 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 10:44:40,764 - INFO - select version()
2021-06-07 10:44:40,764 - INFO - [raw sql] {}
2021-06-07 10:44:40,835 - INFO - select current_schema()
2021-06-07 10:44:40,836 - INFO - [raw sql] {}
2021-06-07 10:44:40,906 - INFO - show standard_conforming_strings
2021-06-07 10:44:40,906 - INFO - [raw sql] {}
2021-06-07 10:44:40,975 - INFO - BEGIN (implicit)
2021-06-07 10:44:40,983 - INFO - SELECT "web-management"."user".id AS "web-management_user_id", "web-management"."user".user_name AS "web-management_user_user_name", "web-management"."user".first_nane AS "web-management_user_first_nane", "web-management"."user".last_name AS "web-management_user_last_name", "web-management"."user".full_nane AS "web-management_user_full_nane", "web-management"."user".email AS "web-management_user_email", "web-management"."user".phone AS "web-management_user_phone", "web-management"."user".password AS "web-management_user_password", "web-management"."user".role_id AS "web-management_user_role_id", "web-management"."user".create_date AS "web-management_user_create_date", "web-management"."user".update_date AS "web-management_user_update_date", role_1.id AS role_1_id, role_1.code AS role_1_code, role_1.name AS role_1_name, role_1.create_date AS role_1_create_date, role_1.update_date AS role_1_update_date 
FROM "web-management"."user" LEFT OUTER JOIN "web-management".role AS role_1 ON role_1.id = "web-management"."user".role_id 
WHERE "web-management"."user".email = %(email_1)s AND "web-management"."user".password = %(password_1)s 
 LIMIT %(param_1)s
2021-06-07 10:44:40,983 - INFO - [generated in 0.00045s] {'email_1': 'duynguyenngoc@hotmail.com', 'password_1': '1q2w3e4r', 'param_1': 1}
2021-06-07 10:44:41,057 - INFO - ROLLBACK
2021-06-07 10:46:30,769 - INFO - BEGIN (implicit)
2021-06-07 10:46:30,771 - INFO - SELECT "web-management"."user".id AS "web-management_user_id", "web-management"."user".user_name AS "web-management_user_user_name", "web-management"."user".first_nane AS "web-management_user_first_nane", "web-management"."user".last_name AS "web-management_user_last_name", "web-management"."user".full_nane AS "web-management_user_full_nane", "web-management"."user".email AS "web-management_user_email", "web-management"."user".phone AS "web-management_user_phone", "web-management"."user".password AS "web-management_user_password", "web-management"."user".role_id AS "web-management_user_role_id", "web-management"."user".create_date AS "web-management_user_create_date", "web-management"."user".update_date AS "web-management_user_update_date", role_1.id AS role_1_id, role_1.code AS role_1_code, role_1.name AS role_1_name, role_1.create_date AS role_1_create_date, role_1.update_date AS role_1_update_date 
FROM "web-management"."user" LEFT OUTER JOIN "web-management".role AS role_1 ON role_1.id = "web-management"."user".role_id 
WHERE "web-management"."user".email = %(email_1)s AND "web-management"."user".password = %(password_1)s 
 LIMIT %(param_1)s
2021-06-07 10:46:30,771 - INFO - [cached since 109.8s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'password_1': '1q2w3e4r', 'param_1': 1}
2021-06-07 10:46:30,811 - INFO - ROLLBACK
2021-06-07 12:44:36,873 - INFO - Shutting down
2021-06-07 12:44:36,974 - INFO - Waiting for application shutdown.
2021-06-07 12:44:36,974 - INFO - Application shutdown complete.
2021-06-07 12:44:36,975 - INFO - Finished server process [4127]
2021-06-07 12:44:38,312 - INFO - Started server process [6661]
2021-06-07 12:44:38,312 - INFO - Waiting for application startup.
2021-06-07 12:44:38,313 - INFO - Application startup complete.
2021-06-07 12:44:38,313 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 12:46:18,841 - INFO - Shutting down
2021-06-07 12:46:18,942 - INFO - Waiting for application shutdown.
2021-06-07 12:46:18,943 - INFO - Application shutdown complete.
2021-06-07 12:46:18,943 - INFO - Finished server process [6661]
2021-06-07 12:46:20,124 - INFO - Started server process [6772]
2021-06-07 12:46:20,125 - INFO - Waiting for application startup.
2021-06-07 12:46:20,125 - INFO - Application startup complete.
2021-06-07 12:46:20,125 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 13:37:37,079 - INFO - Shutting down
2021-06-07 13:37:37,180 - INFO - Waiting for application shutdown.
2021-06-07 13:37:37,181 - INFO - Application shutdown complete.
2021-06-07 13:37:37,181 - INFO - Finished server process [6772]
2021-06-07 13:37:38,936 - INFO - Started server process [7001]
2021-06-07 13:37:38,936 - INFO - Waiting for application startup.
2021-06-07 13:37:38,936 - INFO - Application startup complete.
2021-06-07 13:37:38,937 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 13:42:51,133 - INFO - Shutting down
2021-06-07 13:42:51,233 - INFO - Waiting for application shutdown.
2021-06-07 13:42:51,234 - INFO - Application shutdown complete.
2021-06-07 13:42:51,234 - INFO - Finished server process [7001]
2021-06-07 13:42:52,495 - INFO - Started server process [7185]
2021-06-07 13:42:52,496 - INFO - Waiting for application startup.
2021-06-07 13:42:52,497 - INFO - Application startup complete.
2021-06-07 13:42:52,498 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 13:43:39,200 - INFO - Shutting down
2021-06-07 13:43:39,302 - INFO - Waiting for application shutdown.
2021-06-07 13:43:39,302 - INFO - Application shutdown complete.
2021-06-07 13:43:39,303 - INFO - Finished server process [7185]
2021-06-07 13:43:40,493 - INFO - Started server process [7212]
2021-06-07 13:43:40,493 - INFO - Waiting for application startup.
2021-06-07 13:43:40,493 - INFO - Application startup complete.
2021-06-07 13:43:40,494 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 13:43:53,250 - INFO - Shutting down
2021-06-07 13:43:53,351 - INFO - Waiting for application shutdown.
2021-06-07 13:43:53,352 - INFO - Application shutdown complete.
2021-06-07 13:43:53,353 - INFO - Finished server process [7212]
2021-06-07 13:43:54,663 - INFO - Started server process [7229]
2021-06-07 13:43:54,663 - INFO - Waiting for application startup.
2021-06-07 13:43:54,663 - INFO - Application startup complete.
2021-06-07 13:43:54,664 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 13:44:16,370 - INFO - Shutting down
2021-06-07 13:44:16,472 - INFO - Waiting for application shutdown.
2021-06-07 13:44:16,472 - INFO - Application shutdown complete.
2021-06-07 13:44:16,473 - INFO - Finished server process [7229]
2021-06-07 13:44:17,713 - INFO - Started server process [7247]
2021-06-07 13:44:17,713 - INFO - Waiting for application startup.
2021-06-07 13:44:17,713 - INFO - Application startup complete.
2021-06-07 13:44:17,714 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 13:44:36,598 - INFO - Shutting down
2021-06-07 13:44:36,699 - INFO - Waiting for application shutdown.
2021-06-07 13:44:36,700 - INFO - Application shutdown complete.
2021-06-07 13:44:36,700 - INFO - Finished server process [7247]
2021-06-07 13:44:37,876 - INFO - Started server process [7270]
2021-06-07 13:44:37,876 - INFO - Waiting for application startup.
2021-06-07 13:44:37,876 - INFO - Application startup complete.
2021-06-07 13:44:37,877 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 13:44:48,027 - INFO - Shutting down
2021-06-07 13:44:48,129 - INFO - Finished server process [7270]
2021-06-07 13:44:49,954 - INFO - Started server process [7286]
2021-06-07 13:44:49,954 - INFO - Waiting for application startup.
2021-06-07 13:44:49,955 - INFO - Application startup complete.
2021-06-07 13:44:49,955 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 13:45:31,022 - INFO - Shutting down
2021-06-07 13:45:31,124 - INFO - Finished server process [7286]
2021-06-07 13:45:32,323 - INFO - Started server process [7333]
2021-06-07 13:45:32,323 - INFO - Waiting for application startup.
2021-06-07 13:45:32,324 - INFO - Application startup complete.
2021-06-07 13:45:32,324 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 13:50:24,653 - INFO - Shutting down
2021-06-07 13:50:24,754 - INFO - Waiting for application shutdown.
2021-06-07 13:50:24,755 - INFO - Application shutdown complete.
2021-06-07 13:50:24,755 - INFO - Finished server process [7333]
2021-06-07 13:50:26,824 - INFO - Started server process [7447]
2021-06-07 13:50:26,825 - INFO - Waiting for application startup.
2021-06-07 13:50:26,825 - INFO - Application startup complete.
2021-06-07 13:50:26,825 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 13:53:49,497 - INFO - Shutting down
2021-06-07 13:53:49,598 - INFO - Finished server process [7447]
2021-06-07 13:53:50,870 - INFO - Started server process [7512]
2021-06-07 13:53:50,871 - INFO - Waiting for application startup.
2021-06-07 13:53:50,875 - INFO - Application startup complete.
2021-06-07 13:53:50,876 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 17:24:05,766 - INFO - Shutting down
2021-06-07 17:24:05,867 - INFO - Waiting for application shutdown.
2021-06-07 17:24:05,867 - INFO - Application shutdown complete.
2021-06-07 17:24:05,867 - INFO - Finished server process [7512]
2021-06-07 17:25:36,521 - INFO - Started server process [8097]
2021-06-07 17:25:36,521 - INFO - Waiting for application startup.
2021-06-07 17:25:36,522 - INFO - Application startup complete.
2021-06-07 17:25:36,522 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 17:26:22,415 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 81, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/pot/project/web-management/backend/app/main.py", line 53, in db_session_middleware
    response = await call_next(request)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pot/project/web-management/backend/app/api/resources/v1/operation.py", line 39, in upload
    nas.upload_file(byte_excel, config.NAS_ROOT_PATH + "/test.xlsx")
  File "/home/pot/project/web-management/backend/app/helpers/nas.py", line 44, in upload_file
    pickle.dump(data, buffer)
UnboundLocalError: local variable 'data' referenced before assignment
2021-06-07 17:27:06,048 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 81, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/pot/project/web-management/backend/app/main.py", line 53, in db_session_middleware
    response = await call_next(request)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pot/project/web-management/backend/app/api/resources/v1/operation.py", line 39, in upload
    nas.upload_file(byte_excel, config.NAS_ROOT_PATH + "/test.xlsx")
  File "/home/pot/project/web-management/backend/app/helpers/nas.py", line 44, in upload_file
    pickle.dump(data, buffer)
UnboundLocalError: local variable 'data' referenced before assignment
2021-06-07 17:27:14,470 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 81, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/pot/project/web-management/backend/app/main.py", line 53, in db_session_middleware
    response = await call_next(request)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pot/project/web-management/backend/app/api/resources/v1/operation.py", line 39, in upload
    nas.upload_file(byte_excel, config.NAS_ROOT_PATH + "/test.xlsx")
  File "/home/pot/project/web-management/backend/app/helpers/nas.py", line 44, in upload_file
    pickle.dump(data, buffer)
UnboundLocalError: local variable 'data' referenced before assignment
2021-06-07 17:27:29,316 - INFO - Shutting down
2021-06-07 17:27:29,418 - INFO - Waiting for application shutdown.
2021-06-07 17:27:29,418 - INFO - Application shutdown complete.
2021-06-07 17:27:29,418 - INFO - Finished server process [8097]
2021-06-07 17:27:57,330 - INFO - Started server process [8152]
2021-06-07 17:27:57,331 - INFO - Waiting for application startup.
2021-06-07 17:27:57,331 - INFO - Application startup complete.
2021-06-07 17:27:57,331 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 17:28:02,874 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 81, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/pot/project/web-management/backend/app/main.py", line 53, in db_session_middleware
    response = await call_next(request)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pot/project/web-management/backend/app/api/resources/v1/operation.py", line 39, in upload
    nas.upload_file(byte_excel, config.NAS_ROOT_PATH + "/test.xlsx")
  File "/home/pot/project/web-management/backend/app/helpers/nas.py", line 46, in upload_file
    data = rs.read_from(buffer.getvalue())
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 831, in read_from
    self.client.upload_to(buff=buff, remote_path=self.urn.path())
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 66, in _wrapper
    res = fn(self, *args, **kw)
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 438, in upload_to
    self.execute_request(action='upload', path=urn.quote(), data=buff)
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 226, in execute_request
    raise ResponseErrorCode(url=self.get_url(path), code=response.status_code, message=response.content)
webdav3.exceptions.ResponseErrorCode: Request to https://dwh-staging-shared-drive.digi-texx.vn/nas/pnl/test.xlsx failed with code 401 and message: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>401 Unauthorized</title>\n</head><body>\n<h1>Unauthorized</h1>\n<p>This server could not verify that you\nare authorized to access the document\nrequested.  Either you supplied the wrong\ncredentials (e.g., bad password), or your\nbrowser doesn\'t understand how to supply\nthe credentials required.</p>\n</body></html>\n'
2021-06-07 17:30:44,579 - INFO - Shutting down
2021-06-07 17:30:44,680 - INFO - Waiting for application shutdown.
2021-06-07 17:30:44,681 - INFO - Application shutdown complete.
2021-06-07 17:30:44,681 - INFO - Finished server process [8152]
2021-06-07 17:30:47,124 - INFO - Started server process [8230]
2021-06-07 17:30:47,124 - INFO - Waiting for application startup.
2021-06-07 17:30:47,124 - INFO - Application startup complete.
2021-06-07 17:30:47,125 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 17:30:51,492 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 81, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/pot/project/web-management/backend/app/main.py", line 53, in db_session_middleware
    response = await call_next(request)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pot/project/web-management/backend/app/api/resources/v1/operation.py", line 37, in upload
    nas.upload_file(byte_excel, config.NAS_ROOT_PATH + "/test.xlsx")
  File "/home/pot/project/web-management/backend/app/helpers/nas.py", line 46, in upload_file
    data = rs.read_from(buffer.getvalue())
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 831, in read_from
    self.client.upload_to(buff=buff, remote_path=self.urn.path())
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 66, in _wrapper
    res = fn(self, *args, **kw)
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 438, in upload_to
    self.execute_request(action='upload', path=urn.quote(), data=buff)
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 226, in execute_request
    raise ResponseErrorCode(url=self.get_url(path), code=response.status_code, message=response.content)
webdav3.exceptions.ResponseErrorCode: Request to https://dwh-staging-shared-drive.digi-texx.vn/nas/backup_pnl/test.xlsx failed with code 401 and message: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>401 Unauthorized</title>\n</head><body>\n<h1>Unauthorized</h1>\n<p>This server could not verify that you\nare authorized to access the document\nrequested.  Either you supplied the wrong\ncredentials (e.g., bad password), or your\nbrowser doesn\'t understand how to supply\nthe credentials required.</p>\n</body></html>\n'
2021-06-07 17:31:05,483 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 81, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/pot/project/web-management/backend/app/main.py", line 53, in db_session_middleware
    response = await call_next(request)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pot/project/web-management/backend/app/api/resources/v1/operation.py", line 37, in upload
    nas.upload_file(byte_excel, config.NAS_ROOT_PATH + "/test.xlsx")
  File "/home/pot/project/web-management/backend/app/helpers/nas.py", line 46, in upload_file
    data = rs.read_from(buffer.getvalue())
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 831, in read_from
    self.client.upload_to(buff=buff, remote_path=self.urn.path())
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 66, in _wrapper
    res = fn(self, *args, **kw)
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 438, in upload_to
    self.execute_request(action='upload', path=urn.quote(), data=buff)
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 226, in execute_request
    raise ResponseErrorCode(url=self.get_url(path), code=response.status_code, message=response.content)
webdav3.exceptions.ResponseErrorCode: Request to https://dwh-staging-shared-drive.digi-texx.vn/nas/backup_pnl/test.xlsx failed with code 401 and message: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>401 Unauthorized</title>\n</head><body>\n<h1>Unauthorized</h1>\n<p>This server could not verify that you\nare authorized to access the document\nrequested.  Either you supplied the wrong\ncredentials (e.g., bad password), or your\nbrowser doesn\'t understand how to supply\nthe credentials required.</p>\n</body></html>\n'
2021-06-07 17:31:44,973 - INFO - Shutting down
2021-06-07 17:31:45,074 - INFO - Waiting for application shutdown.
2021-06-07 17:31:45,075 - INFO - Application shutdown complete.
2021-06-07 17:31:45,075 - INFO - Finished server process [8230]
2021-06-07 17:31:46,323 - INFO - Started server process [8286]
2021-06-07 17:31:46,324 - INFO - Waiting for application startup.
2021-06-07 17:31:46,325 - INFO - Application startup complete.
2021-06-07 17:31:46,325 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 17:36:07,224 - INFO - Shutting down
2021-06-07 17:36:07,325 - INFO - Waiting for application shutdown.
2021-06-07 17:36:07,326 - INFO - Application shutdown complete.
2021-06-07 17:36:07,327 - INFO - Finished server process [8286]
2021-06-07 17:41:55,743 - INFO - Started server process [8455]
2021-06-07 17:41:55,744 - INFO - Waiting for application startup.
2021-06-07 17:41:55,744 - INFO - Application startup complete.
2021-06-07 17:41:55,744 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 18:01:48,771 - INFO - Shutting down
2021-06-07 18:01:48,872 - INFO - Waiting for application shutdown.
2021-06-07 18:01:48,873 - INFO - Application shutdown complete.
2021-06-07 18:01:48,873 - INFO - Finished server process [8455]
2021-06-07 18:01:50,169 - INFO - Started server process [8807]
2021-06-07 18:01:50,170 - INFO - Waiting for application startup.
2021-06-07 18:01:50,170 - INFO - Application startup complete.
2021-06-07 18:01:50,171 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 18:01:59,076 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 81, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/pot/project/web-management/backend/app/main.py", line 53, in db_session_middleware
    response = await call_next(request)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pot/project/web-management/backend/app/api/resources/v1/operation.py", line 47, in upload
    nas.upload_file(byte_excel, config.NAS_ROOT_PATH + "/{str_year}{str_month}/path-0.pickle".format(str_year = str_year, str_month = str_month))
  File "/home/pot/project/web-management/backend/app/helpers/nas.py", line 46, in upload_file
    data = rs.read_from(buffer.getvalue())
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 831, in read_from
    self.client.upload_to(buff=buff, remote_path=self.urn.path())
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 66, in _wrapper
    res = fn(self, *args, **kw)
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 438, in upload_to
    self.execute_request(action='upload', path=urn.quote(), data=buff)
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 226, in execute_request
    raise ResponseErrorCode(url=self.get_url(path), code=response.status_code, message=response.content)
webdav3.exceptions.ResponseErrorCode: Request to https://dwh-staging-shared-drive.digi-texx.vn/nas/pnl/202106/path-0.pickle failed with code 401 and message: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>401 Unauthorized</title>\n</head><body>\n<h1>Unauthorized</h1>\n<p>This server could not verify that you\nare authorized to access the document\nrequested.  Either you supplied the wrong\ncredentials (e.g., bad password), or your\nbrowser doesn\'t understand how to supply\nthe credentials required.</p>\n</body></html>\n'
2021-06-07 18:04:32,260 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 81, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/pot/project/web-management/backend/app/main.py", line 53, in db_session_middleware
    response = await call_next(request)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pot/project/web-management/backend/app/api/resources/v1/operation.py", line 47, in upload
    nas.upload_file(byte_excel, config.NAS_ROOT_PATH + "/{str_year}{str_month}/path-0.pickle".format(str_year = str_year, str_month = str_month))
  File "/home/pot/project/web-management/backend/app/helpers/nas.py", line 46, in upload_file
    data = rs.read_from(buffer.getvalue())
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 831, in read_from
    self.client.upload_to(buff=buff, remote_path=self.urn.path())
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 66, in _wrapper
    res = fn(self, *args, **kw)
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 438, in upload_to
    self.execute_request(action='upload', path=urn.quote(), data=buff)
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 226, in execute_request
    raise ResponseErrorCode(url=self.get_url(path), code=response.status_code, message=response.content)
webdav3.exceptions.ResponseErrorCode: Request to https://dwh-staging-shared-drive.digi-texx.vn/nas/pnl/202106/path-0.pickle failed with code 401 and message: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>401 Unauthorized</title>\n</head><body>\n<h1>Unauthorized</h1>\n<p>This server could not verify that you\nare authorized to access the document\nrequested.  Either you supplied the wrong\ncredentials (e.g., bad password), or your\nbrowser doesn\'t understand how to supply\nthe credentials required.</p>\n</body></html>\n'
2021-06-07 18:06:18,867 - INFO - Shutting down
2021-06-07 18:06:18,968 - INFO - Waiting for application shutdown.
2021-06-07 18:06:18,969 - INFO - Application shutdown complete.
2021-06-07 18:06:18,969 - INFO - Finished server process [8807]
2021-06-07 18:06:20,366 - INFO - Started server process [8862]
2021-06-07 18:06:20,366 - INFO - Waiting for application startup.
2021-06-07 18:06:20,367 - INFO - Application startup complete.
2021-06-07 18:06:20,367 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 18:10:19,205 - INFO - Shutting down
2021-06-07 18:10:19,307 - INFO - Waiting for application shutdown.
2021-06-07 18:10:19,307 - INFO - Application shutdown complete.
2021-06-07 18:10:19,307 - INFO - Finished server process [8862]
2021-06-07 18:10:20,670 - INFO - Started server process [8933]
2021-06-07 18:10:20,670 - INFO - Waiting for application startup.
2021-06-07 18:10:20,671 - INFO - Application startup complete.
2021-06-07 18:10:20,671 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 18:28:29,406 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 81, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/pot/project/web-management/backend/app/main.py", line 53, in db_session_middleware
    response = await call_next(request)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/pot/.local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/pot/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pot/project/web-management/backend/app/api/resources/v1/operation.py", line 52, in upload
    nas.upload_file(byte_excel, config.NAS_ROOT_PATH + "/{str_year}{str_month}/{str_year}-{str_month}-{str_day}.pickle".format(str_year = str_year, str_month = str_month, str_day = str_day))
  File "/home/pot/project/web-management/backend/app/helpers/nas.py", line 46, in upload_file
    data = rs.read_from(buffer.getvalue())
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 831, in read_from
    self.client.upload_to(buff=buff, remote_path=self.urn.path())
  File "/home/pot/.local/lib/python3.9/site-packages/webdav3/client.py", line 68, in _wrapper
    raise NoConnection(self.webdav.hostname)
webdav3.exceptions.NoConnection: No connection with https://dwh-staging-shared-drive.digi-texx.vn/nas
2021-06-07 19:39:36,297 - INFO - Shutting down
2021-06-07 19:39:36,398 - INFO - Waiting for application shutdown.
2021-06-07 19:39:36,398 - INFO - Application shutdown complete.
2021-06-07 19:39:36,399 - INFO - Finished server process [8933]
2021-06-07 19:39:37,668 - INFO - Started server process [8972]
2021-06-07 19:39:37,669 - INFO - Waiting for application startup.
2021-06-07 19:39:37,669 - INFO - Application startup complete.
2021-06-07 19:39:37,670 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 19:54:36,653 - INFO - Started server process [141]
2021-06-07 19:54:36,654 - INFO - Waiting for application startup.
2021-06-07 19:54:36,655 - INFO - Application startup complete.
2021-06-07 19:54:36,655 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 20:50:15,377 - INFO - Shutting down
2021-06-07 20:50:15,478 - INFO - Waiting for application shutdown.
2021-06-07 20:50:15,478 - INFO - Application shutdown complete.
2021-06-07 20:50:15,478 - INFO - Finished server process [141]
2021-06-07 20:50:16,830 - INFO - Started server process [957]
2021-06-07 20:50:16,830 - INFO - Waiting for application startup.
2021-06-07 20:50:16,831 - INFO - Application startup complete.
2021-06-07 20:50:16,831 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 20:51:06,443 - INFO - Shutting down
2021-06-07 20:51:06,544 - INFO - Waiting for application shutdown.
2021-06-07 20:51:06,545 - INFO - Application shutdown complete.
2021-06-07 20:51:06,545 - INFO - Finished server process [957]
2021-06-07 20:51:07,922 - INFO - Started server process [979]
2021-06-07 20:51:07,923 - INFO - Waiting for application startup.
2021-06-07 20:51:07,923 - INFO - Application startup complete.
2021-06-07 20:51:07,924 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2021-06-07 20:55:54,423 - INFO - Shutting down
2021-06-07 20:55:54,524 - INFO - Waiting for application shutdown.
2021-06-07 20:55:54,525 - INFO - Application shutdown complete.
2021-06-07 20:55:54,525 - INFO - Finished server process [979]
2021-06-07 20:55:57,536 - INFO - Started server process [1063]
2021-06-07 20:55:57,537 - INFO - Waiting for application startup.
2021-06-07 20:55:57,537 - INFO - Application startup complete.
2021-06-07 20:55:57,537 - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
